/**
 * Every foreground the specifications put on a background, with the contrast it needs: text 4.5:1; focus rings,
 * control outlines and chart marks 3:1 (WCAG 1.4.11). A background given as a list is composited in order over the
 * ground. Pure data, so the contrast gate and the Atlas's colour page measure the same pairs.
 */
export const TEXT = 4.5, UI = 3;
export type Pair = [fg: string, bg: string | string[], min: number, what: string];

export const PAIRS: Pair[] = [
  ['ink', 'ground', TEXT, 'body text on the page'],
  ['ink', 'surface', TEXT, 'body text in a card'],
  ['ink', 'surface-raised', TEXT, 'text in a menu or dialog'],
  ['ink-2', 'ground', TEXT, 'secondary copy on the page'],
  ['ink-2', 'surface', TEXT, 'secondary copy and inactive navigation'],
  ['ink-2', 'surface-sunk', TEXT, 'a segmented option at rest'],
  ['ink-2', ['frame'], TEXT, 'inactive navigation in the rail'],
  ['ink-3', ['frame'], TEXT, 'a group label in the rail'],
  ['accent-ink', ['frame', 'accent-tint'], TEXT, 'the active navigation label in the rail'],
  ['ink-3', 'ground', TEXT, 'captions on the page'],
  ['ink-3', 'surface', TEXT, 'axis ticks, captions and placeholders in a card'],
  ['ink-3', 'surface-sunk', TEXT, 'a table head'],
  ['ink-3', 'surface-raised', TEXT, 'a shortcut hint in a menu'],
  ['ink', ['surface', 'fill-hover'], TEXT, 'a row under the pointer'],
  ['ink-inverse', 'surface-inverse', TEXT, 'tooltip text'],
  ['on-accent', 'accent', TEXT, 'primary button label'],
  ['on-accent', 'accent-hover', TEXT, 'primary button label on hover'],
  ['accent-ink', 'surface', TEXT, 'an inline link in a card'],
  ['accent-ink', 'ground', TEXT, 'an inline link on the page'],
  ['accent-ink', ['surface', 'accent-tint'], TEXT, 'the active navigation label'],
  ['ink', ['surface', 'accent-tint'], TEXT, 'a selected row'],
  ['ink-2', ['surface', 'accent-tint'], TEXT, 'muted text in a selected row or on an accent wash (ink-3 is not enough there)'],
  ['ink-2', ['surface', 'fill-track'], TEXT, 'a count on an inactive tab'],
  ['positive-ink', 'surface', TEXT, 'an improving delta'],
  ['positive-ink', ['surface', 'positive-tint'], TEXT, 'a positive badge'],
  ['warning-ink', 'surface', TEXT, 'a warning message'],
  ['warning-ink', ['surface', 'warning-tint'], TEXT, 'a warning badge'],
  ['critical-ink', 'surface', TEXT, 'an error message'],
  ['critical-ink', 'ground', TEXT, 'an error under a field on the page'],
  ['critical-ink', ['surface', 'critical-tint'], TEXT, 'a critical badge'],
  ['on-critical', 'critical-fill', TEXT, 'the destructive button label'],
  ['accent', 'surface', UI, 'focus ring, active marker and the highlighted mark in a card'],
  ['accent', 'ground', UI, 'focus ring on the page'],
  ['line-control', 'surface', UI, 'a checkbox or radio at rest'],
  ['positive', 'surface', UI, 'a positive status dot'],
  ['warning', 'surface', UI, 'a warning status dot'],
  ['critical', 'surface', UI, 'a critical status dot'],
  ['chart-neutral-strong', 'surface', UI, 'a neutral comparison line'],
  ['series-1', 'surface', UI, 'chart slot 1'],
  ['series-2', 'surface', UI, 'chart slot 2'],
  ['series-3', 'surface', UI, 'chart slot 3'],
  ['series-4', 'surface', UI, 'chart slot 4'],
  ['series-6', 'surface', UI, 'chart slot 6'],
];
