/**
 * Generate src/system/registry.ts: every card folder (a README.md beside an index.tsx) in the component layers, with a
 * lazy import of its preview. The Atlas reads it; nothing else does. Also, for the bare preview route: the same previews
 * as client loaders by "section/id" (src/system/preview-loaders.ts) and their plain list of keys, which the server page
 * reads for its static params and its not-found (app/system/preview/[section]/[card]/keys.ts). The server page names no
 * preview, so the route's first load carries one card's chunks, not all of them.
 *
 *   node scripts/registry.ts           write all three
 *   node scripts/registry.ts --check   exit 1 if any is out of date or a card is missing its preview
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const LAYERS = [
  { dir: 'src/components/base', layer: 1, section: 'base' },
  { dir: 'src/components/ui', layer: 2, section: 'components' },
  { dir: 'src/components/patterns', layer: 3, section: 'patterns' },
  { dir: 'src/components/charts', layer: 3, section: 'patterns' },
] as const;

type CardEntry = { id: string; layer: number; section: string; dir: string; hasPreview: boolean };

export function cards(): CardEntry[] {
  const out: CardEntry[] = [];
  for (const l of LAYERS) {
    const abs = path.join(ROOT, l.dir);
    for (const name of fs.readdirSync(abs).sort()) {
      const d = path.join(abs, name);
      if (!fs.statSync(d).isDirectory() || !fs.existsSync(path.join(d, 'README.md'))) continue;
      out.push({ id: name, layer: l.layer, section: l.section, dir: `${l.dir}/${name}`, hasPreview: fs.existsSync(path.join(d, 'preview.tsx')) });
    }
  }
  return out;
}

const REGISTRY = 'src/system/registry.ts';
const LOADERS = 'src/system/preview-loaders.ts';
const KEYS = 'app/system/preview/[section]/[card]/keys.ts';

function build() {
  const list = cards();
  const lines = [
    '/* GENERATED by scripts/registry.ts from the card folders. Do not edit. */',
    "import dynamic from 'next/dynamic';",
    "import type { ComponentType } from 'react';",
    '',
    'type Card = { id: string; layer: number; section: string; dir: string; Preview: ComponentType | null };',
    '',
    'export const CARDS: Card[] = [',
    ...list.map((c) => `  { id: '${c.id}', layer: ${c.layer}, section: '${c.section}', dir: '${c.dir}', Preview: ${c.hasPreview ? `dynamic(() => import('@/${c.dir.replace(/^src\//, '')}/preview'))` : 'null'} },`),
    '];',
    '',
  ];
  return lines.join('\n');
}

function buildLoaders() {
  const lines = [
    '/* GENERATED by scripts/registry.ts from the card folders. Do not edit. */',
    "'use client';",
    '',
    "import type { ComponentType } from 'react';",
    '',
    '/** Every card preview by "section/id", loaded in the browser for the one card the route renders. */',
    'export const PREVIEW_LOADERS: Record<string, () => Promise<{ default: ComponentType }>> = {',
    ...cards().filter((c) => c.hasPreview).map((c) => `  '${c.section}/${c.id}': () => import('@/${c.dir.replace(/^src\//, '')}/preview'),`),
    '};',
    '',
  ];
  return lines.join('\n');
}

function buildKeys() {
  const lines = [
    '/* GENERATED by scripts/registry.ts from the card folders. Do not edit. */',
    '/** The "section/id" of every card with a preview: a plain list, so the server page never imports a preview. */',
    'export const PREVIEW_KEYS: string[] = [',
    ...cards().filter((c) => c.hasPreview).map((c) => `  '${c.section}/${c.id}',`),
    '];',
    '',
  ];
  return lines.join('\n');
}

if (import.meta.main) {
  // The preview route's files exist only where the route does (brand.ts --no-atlas removes app/system and keeps the registry).
  const route = fs.existsSync(path.join(ROOT, path.dirname(KEYS)));
  const outputs = [
    { rel: REGISTRY, file: path.join(ROOT, REGISTRY), next: build() },
    ...(route ? [
      { rel: LOADERS, file: path.join(ROOT, LOADERS), next: buildLoaders() },
      { rel: KEYS, file: path.join(ROOT, KEYS), next: buildKeys() },
    ] : []),
  ];
  if (process.argv.includes('--check')) {
    const missing = cards().filter((c) => !c.hasPreview).map((c) => c.dir);
    const stale = outputs.filter((o) => !fs.existsSync(o.file) || fs.readFileSync(o.file, 'utf8') !== o.next);
    for (const o of stale) console.log(`${o.rel} is out of date: run node scripts/registry.ts`);
    for (const m of missing) console.log(`${m}: no preview.tsx`);
    console.log(stale.length || missing.length ? '' : `registry: ${cards().length} cards, all with previews`);
    process.exit(stale.length || missing.length ? 1 : 0);
  }
  for (const o of outputs) fs.writeFileSync(o.file, o.next);
  console.log(`${outputs.map((o) => o.rel).join(', ')}: ${cards().length} cards`);
}
